# Generated by Django 5.1.1 on 2024-10-03 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0007_rating_five_stars_rating_four_stars'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='percentage',
            field=models.FloatField(default=0.0),
        ),
    ]
