# Generated by Django 5.1.1 on 2024-10-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0009_rating_voters'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='race_weekend',
            new_name='event_list',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('qualifying', 'Qualifying'), ('race', 'Race'), ('shootout', 'Sprint Shootout'), ('sprint', 'Sprint Race'), ('match', 'Match')], max_length=10),
        ),
    ]
