# Generated by Django 5.1.1 on 2024-10-05 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0014_alter_event_event_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='round',
        ),
    ]
