# Generated by Django 5.1.1 on 2024-10-09 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0018_event_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='video',
            new_name='video_id',
        ),
    ]
