# Generated by Django 5.1.5 on 2026-07-07 02:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_commentvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='ai_rating',
        ),
        migrations.RemoveField(
            model_name='event',
            name='ai_review',
        ),
    ]
