# Generated by Django 5.1.1 on 2024-11-05 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_competition_poster_event_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='poster',
            field=models.CharField(default='', max_length=255),
        ),
    ]
