# Generated by Django 5.1.1 on 2024-11-05 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_competition_poster'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competition',
            name='poster',
        ),
    ]
