# Generated by Django 5.1.1 on 2024-11-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_remove_competition_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='ai_rating',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='event',
            name='ai_review',
            field=models.TextField(default='', null=True),
        ),
    ]
