# Generated by Django 5.1.1 on 2024-10-03 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0006_alter_rating_unique_together_rating_one_star_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='five_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='four_stars',
            field=models.IntegerField(default=0),
        ),
    ]
