# Generated by Django 5.1.1 on 2024-10-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0017_remove_competition_idevent_event_idevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='video',
            field=models.CharField(default='', max_length=255),
        ),
    ]
