# Generated by Django 5.1.5 on 2026-06-22 05:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0002_commentvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSignals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signals', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='core.event')),
            ],
            options={
                'verbose_name': '⚠ Event Signals [INTERNAL]',
                'verbose_name_plural': '⚠ Event Signals [INTERNAL]',
            },
        ),
    ]
