# Generated by Django 5.1.5 on 2026-06-22 07:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airatings', '0001_initial'),
        ('core', '0002_commentvote'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending_review', 'Pending Review'), ('published', 'Published'), ('flagged', 'Flagged — Manual Review Required')], db_index=True, default='pending_review', max_length=20)),
                ('stars', models.IntegerField()),
                ('verdict', models.CharField(max_length=20)),
                ('blurb', models.TextField()),
                ('rationale_internal', models.TextField()),
                ('flag_reasons', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ai_pipeline', to='core.event')),
            ],
            options={
                'verbose_name': 'AI Rating',
                'verbose_name_plural': 'AI Ratings',
            },
        ),
    ]
