# Generated by Django 5.1.5 on 2026-06-24 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('airatings', '0002_airating'),
    ]

    operations = [
        migrations.AddField(
            model_name='airating',
            name='dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='airating',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
