# Generated by Django 5.1.5 on 2026-06-19 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gamify', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xpevent',
            name='action_type',
            field=models.CharField(choices=[('comment_posted', 'Posted a comment'), ('reply_posted', 'Posted a reply'), ('event_rated', 'Rated an event'), ('event_rated_early', 'Rated within 1 hour of event finishing (bonus)'), ('event_liked', 'Liked/disliked an event'), ('rating_liked', 'Your event rating received a like'), ('comment_liked', 'Comment received a like'), ('daily_bonus', 'First action of the day'), ('badge_awarded', 'Badge unlocked')], max_length=50),
        ),
    ]
