# Generated by Django 5.1.1 on 2024-10-02 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('event', 'user')},
        ),
        migrations.AlterField(
            model_name='event',
            name='race_weekend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='f1.race'),
        ),
        migrations.DeleteModel(
            name='RaceWeekend',
        ),
    ]
