# Generated by Django 5.1.1 on 2024-10-02 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0005_alter_event_event_type'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='rating',
            name='one_star',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='three_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='rating',
            name='two_stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='rating',
            name='event',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rating', to='f1.event'),
        ),
        migrations.RemoveField(
            model_name='rating',
            name='score',
        ),
        migrations.RemoveField(
            model_name='rating',
            name='user',
        ),
    ]
