# Generated by Django 5.1.1 on 2024-10-03 15:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0008_rating_percentage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='voters',
            field=models.ManyToManyField(related_name='rated_events', to=settings.AUTH_USER_MODEL),
        ),
    ]
