# Generated by Django 5.1.1 on 2024-10-04 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('f1', '0010_rename_race_weekend_event_event_list_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Race',
            new_name='Competition',
        ),
    ]
