# Generated by Django 5.1.1 on 2024-10-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='league',
            field=models.CharField(default='', max_length=255),
        ),
    ]
