# Generated by Django 5.1.1 on 2024-10-13 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_event_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='video_id',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
