# Generated by Django 5.1.1 on 2024-10-13 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_event_video_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='finished',
            new_name='is_finished',
        ),
    ]
