# Generated by Django 5.1.1 on 2024-10-14 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_finished_event_is_finished'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competition',
            unique_together={('name', 'date')},
        ),
    ]
