# Generated by Django 5.1.1 on 2024-10-14 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_competition_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='competition',
            unique_together=set(),
        ),
    ]
