# Generated by Django 5.1.1 on 2024-11-05 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_result_f1'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='badge',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='competition',
            name='banner',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='competition',
            name='poster',
            field=models.CharField(default='', max_length=255),
        ),
    ]
